/**
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
*
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
* By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*
* Output: 4613730
* Why you chose the problems you did:
* This is a second problem
* A description of the process you followed in solving the problem:
* count each fibonacci number, if it is an even one, add it up
* How much time you spent on the exercise:
* 10 minutes
*/


public class Problem2{
	//sum up even fibonacci numbers
	public int evenFibNum(int max){
		int fib1 = 1;
		int fib2 = 2;
		int fib3;
		int sum = 0;
		while((fib3 = fib1 + fib2) < max){
			if(fib3 % 2 == 0){
				sum += fib3;
			}
			fib1 = fib2;
			fib2 = fib3;
		}
		return sum;
	}
	public static void main(String[] args){
		int result;
		Problem2 p2 = new Problem2();
		result = p2.evenFibNum(4000000);
		System.out.println(result);
	}
}
